server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  application:
    name: customer

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password:

  security:
    user:
      name: T
      password: 1234
      roles: admin
  loan:
    host: http://localhost:8082/api/loan
    endpoint:
      getInfo: info

restTemplate:
  connectionTimeOut : 5000
  readTimeOut: 10000